### ISSUE TITLE
init error on haiku-os beta4 64 bit

### ISSUE THREAD

**Issue by armgong** [DonAnthonyLee/BeSunPinyin#2]
install libsunpinyin using pkgman.
git clone ,build ,install  besunpinyin  , but it can't start on haiku-os beta4 64 bit .
![image](https://user-images.githubusercontent.com/4819374/210480162-05c200c0-5589-4838-92a0-39516a7356fe.png).

**Comment by armgong** [comment]
btw, I also tried update libsunpinyin  to github master branch , compiled it ok.
~~~bash
scons --prefix=/boot/system/non-packaged install
~~~
and rebuild besunpinyin with new libsunpinyin  this time no error and IME icon appeared. 
but input methods window show null , can't select any method.
and I tried copy two sunpinyin dict file to
~~~bash
 /boot/config/non-packaged/data 
 /boot/config/non-packaged/lib 
 /boot/config/non-packaged/share
/boot/system/non-packaged/data 
 /boot/system/non-packaged/lib 
 /boot/system/non-packaged/share
~~~
still no input method show and can select

**Comment by armgong** [comment]
找到原因了，是haiku-os的问题。如果使用系统设置中的 locale 设置语言为中文。
那么无论是becjk还是besunpinyin都会没有输入方法选择。
如果把locale改为英文那么输入法一切正常
![其他 64 位-2023-01-04-21-39-55](https://user-images.githubusercontent.com/4819374/210568700-e1afc7ce-ada3-4457-8875-5a7bbe3c8905.png)
![其他 64 位-2023-01-04-21-40-55](https://user-images.githubusercontent.com/4819374/210568703-aeb59405-5130-4c24-af95-51ed8e9a1617.png)

**Comment by DonAnthonyLee** [comment]
是的，如果 locale 是中文时确实无法加载 input add-on，具体原因未探究。
test 子目录有一个单独的测试程序，可用来确定 libsunpinyin 的问题。

**Comment by DonAnthonyLee** [comment]
> 找到原因了，是haiku-os的问题。如果使用系统设置中的 locale 设置语言为中文。 那么无论是becjk还是besunpinyin都会没有输入方法选择。 如果把locale改为英文那么输入法一切正常 ![其他 64 位-2023-01-04-21-39-55](https://user-images.githubusercontent.com/4819374/210568700-e1afc7ce-ada3-4457-8875-5a7bbe3c8905.png) ![其他 64 位-2023-01-04-21-40-55](https://user-images.githubusercontent.com/4819374/210568703-aeb59405-5130-4c24-af95-51ed8e9a1617.png)

Patch for Deskbar of Haiku:
````
diff --git a/src/apps/deskbar/BarWindow.cpp b/src/apps/deskbar/BarWindow.cpp
index 418384de..bf88dcdf 100644
--- a/src/apps/deskbar/BarWindow.cpp
+++ b/src/apps/deskbar/BarWindow.cpp
@@ -85,7 +85,7 @@ TDeskbarMenu* TBarWindow::sDeskbarMenu = NULL;
 TBarWindow::TBarWindow()
        :
        BWindow(BRect(-1000.0f, -1000.0f, -1000.0f, -1000.0f),
-               B_TRANSLATE_SYSTEM_NAME("Deskbar"), B_BORDERED_WINDOW,
+               "Deskbar", B_BORDERED_WINDOW,
                B_WILL_ACCEPT_FIRST_CLICK | B_NOT_ZOOMABLE | B_NOT_CLOSABLE
                        | B_NOT_MINIMIZABLE | B_NOT_MOVABLE | B_NOT_V_RESIZABLE
                        | B_AVOID_FRONT | B_ASYNCHRONOUS_CONTROLS,
````
